"""Render all paper figures and tables from collected experiment data.

    python -m iosp.make_figures
    python -m iosp.make_figures --only fig2_multistart
"""

import argparse
import os
import sys
import traceback

FIGURES_DIR = os.path.join(os.path.dirname(__file__), "figures")
RESULTS_DIR = os.path.join(os.path.dirname(__file__), "data", "results")

# Curated paper slate (EXPERIMENT_PLAN.md v2). Renderers for figures that
# were dropped from the slate (`iosp.viz.fig_tamp2d`, `iosp.viz.fig_ablation`,
# `iosp.analysis.table_robustness`) are deliberately still in the tree and
# still runnable by hand -- they are just no longer paper deliverables, so
# they are not generated by default.
RENDERERS = [
    {
        # Flagship example: pick-place recovery, loss-vs-step + EE path.
        "name": "fig2_multistart",
        "renderer": "iosp.viz.fig_multistart",
        "input": os.path.join(RESULTS_DIR, "multistart", "joint_seed0.npz"),
        "out": os.path.join(FIGURES_DIR, "fig2_multistart.pdf"),
    },
    {
        # Cross-domain aggregate: pick-place / tetris / block stacking.
        "name": "table_domains",
        "renderer": "iosp.analysis.table_domains",
        "input": RESULTS_DIR,
        "out": os.path.join(FIGURES_DIR, "table_domains.tex"),
    },
    {
        # Subspace-reconstruction theory figure: Gram spectrum + eigen-
        # projected error under rank deficiency.
        "name": "fig_eigenspectrum",
        "renderer": "iosp.viz.fig_eigenspectrum",
        "input": os.path.join(RESULTS_DIR, "identifiability",
                              "eigen_projection.npz"),
        "out": os.path.join(FIGURES_DIR, "fig_eigenspectrum.pdf"),
    },
]


def render_one(entry):
    name = entry["name"]
    print(f"\n[render] {name}: {entry['renderer']} -> {entry['out']}")
    try:
        mod = __import__(entry["renderer"], fromlist=["render"])
        os.makedirs(os.path.dirname(entry["out"]) or ".", exist_ok=True)
        mod.render(entry["input"], entry["out"])
        print(f"  done: {entry['out']}")
        return True
    except FileNotFoundError as e:
        print(f"  SKIP (missing data): {e}")
        return False
    except Exception:
        traceback.print_exc()
        print(f"  FAILED")
        return False


def main():
    ap = argparse.ArgumentParser(description="Render all IOSP paper figures")
    ap.add_argument("--only",
                    help="Comma-separated figure names to render")
    args = ap.parse_args()

    os.makedirs(FIGURES_DIR, exist_ok=True)

    targets = RENDERERS
    if args.only:
        want = [n.strip() for n in args.only.split(",") if n.strip()]
        targets = [r for r in RENDERERS if r["name"] in want]
        missing = [n for n in want if n not in {r["name"] for r in RENDERERS}]
        if missing:
            print(f"Unknown figure(s): {', '.join(missing)}")
            print(f"Available: {', '.join(r['name'] for r in RENDERERS)}")
            sys.exit(1)

    ok, fail = 0, 0
    for entry in targets:
        if render_one(entry):
            ok += 1
        else:
            fail += 1

    print(f"\n{ok} rendered, {fail} skipped/failed")


if __name__ == "__main__":
    main()
