"""Ground-truth recovery benchmark for the composed pick-and-place planner.

Validates the implicit-adjoint outer loop against a KNOWN theta (not against
finite differences -- see `iosp/pickplace.py`'s module docstring: the FD check
on this composed IK->trajopt chain disagrees badly with the implicit adjoint
even after three separate hard-branch-to-soft fixes in the trajopt forward
solver, cos(implicit, FD) stuck around -0.71, and a float64 test of the
"FD is just float32-noise-swamped" hypothesis is blocked by `canonical_ik`'s
custom_jvp being float32-only regardless of caller dtype discipline -- a real,
documented, open constraint, not something this script works around).  FD
agreement is NOT the validation standard here; recovering a KNOWN theta_star
from a synthetic demo generated by the SAME composed model is:

    theta_star -> composed forward rollout -> synthetic demo (ground truth,
    zero ambiguity about what "correct" recovery means)
    demo -> outer loop (implicit-gradient Adam, or CMA-ES) -> theta_hat
    score: ||theta_hat - theta_star|| and EE-path reconstruction RMSE

CMA-ES is the implicit-diff-agnostic baseline: it never touches the adjoint,
so if implicit reaches comparable recovery quality at far fewer forward
solves, that's evidence the implicit gradient is directionally useful in
practice, independent of whether it agrees with FD.

Timing methodology (measured to matter): the naive "time the whole Adam loop"
number is dominated by one-time JIT compilation, not steady-state solve cost
-- an early run of this benchmark reported 111s/Adam-step, which is not a
real per-step cost, it's a single ~110s compile amortized as if it were 12
separate expensive steps.  This script times compile and steady-state
separately: one throwaway call to the jitted loss/grad function BEFORE the
timed region, then the outer loop measured only after that cache is warm.

Usage:
    CUDA_VISIBLE_DEVICES=<idx> XLA_PYTHON_CLIENT_PREALLOCATE=false \\
        python -m iosp.recovery_bench
"""

import pathlib
import time

import jax
import jax.numpy as jnp
import numpy as np

from ioc import metrics, outer as outer_opt
from ioc.inner import make_inner_solver
from iosp import pickplace as pp

RESOURCE_ROOT = pathlib.Path(__file__).resolve().parent.parent / "resources"
URDF_PATH = RESOURCE_ROOT / "panda" / "panda_spherized.urdf"
SRDF_PATH = RESOURCE_ROOT / "panda" / "panda.srdf"
MESH_DIR = RESOURCE_ROOT / "panda" / "meshes"

# The one ground-truth theta this benchmark is defined against.  Changing
# these changes what "correct recovery" means, so they are named constants,
# not CLI args -- pin a scene here rather than sampling one, since a single
# ground-truth demo is exactly what the teleop example also produces.
THETA_IK_STAR = jnp.array([0.06, 0.04], dtype=jnp.float32)
Z_TRAJOPT_STAR = jnp.array([1.0, 2.0, 0.5, 1.0, 2.0, 0.5, 1.0], dtype=jnp.float32)
Q_START = jnp.array([0.0, -0.6, 0.0, -2.2, 0.0, 1.6, 0.8], dtype=jnp.float32)
PICK_POS = jnp.array([0.4, 0.2, 0.3], dtype=jnp.float32)
PLACE_POS = jnp.array([0.4, -0.2, 0.3], dtype=jnp.float32)
OBS_CENTER = jnp.array([0.3, 0.0, 0.4], dtype=jnp.float32)
OBS_RADIUS = jnp.array([0.05], dtype=jnp.float32)

N_STEPS_IMPLICIT = 12  # Adam steps -> 12 forward solves
N_GENS_CMAES = 12  # CMA-ES generations; solves = n_gens * lambda(K=9) = 12*10 = 120


def _split_trajopt(theta_trajopt):
    out, i = {}, 0
    for p in pp.PHASES:
        n = len(pp.SEGMENT_FEATURES[p])
        out[p] = theta_trajopt[i : i + n]
        i += n
    return out


def _unpack_z(z):
    return z[: pp.K_IK], z[pp.K_IK :]


def run(n_steps_implicit=N_STEPS_IMPLICIT, n_gens_cmaes=N_GENS_CMAES, seed=0):
    prob = pp.PickPlaceProblem.load(str(URDF_PATH), str(SRDF_PATH), str(MESH_DIR))
    scene1 = pp.PickPlaceScene(
        q_start=Q_START, pick_pos=PICK_POS, place_pos=PLACE_POS,
        obs_center=OBS_CENTER, obs_radius=OBS_RADIUS,
    )
    scenes = jax.tree.map(lambda a: a[None], scene1)
    forward_solver = pp.make_composed_forward_solver(n_iters=60)

    theta_trajopt_star = jax.nn.softmax(Z_TRAJOPT_STAR)
    x0_star, phase_scenes_star, _, _ = prob.seeds(scenes, THETA_IK_STAR)

    inner_by_phase = {}
    for p in pp.PHASES:
        residual_fn, _ = prob.make_segment_inner(p, forward_solver)
        scales = prob.calibrate_segment(p, residual_fn, phase_scenes_star[p], jax.random.PRNGKey(seed))
        inner_by_phase[p] = make_inner_solver(residual_fn, scales, forward_solver=forward_solver)

    _, _, xs_gt, phase_scenes_gt = prob.solve(
        THETA_IK_STAR, _split_trajopt(theta_trajopt_star), scenes, inner_by_phase, x0_star)
    demo_path = prob.full_ee_path(scenes, xs_gt, phase_scenes_gt, batch_index=0)

    def loss(z):
        theta_ik, z_trajopt = _unpack_z(z)
        theta_trajopt_by_phase = _split_trajopt(jax.nn.softmax(z_trajopt))
        x0, phase_scenes, _, _ = prob.seeds(scenes, theta_ik)
        _, _, xs, phase_scenes2 = prob.solve(theta_ik, theta_trajopt_by_phase, scenes, inner_by_phase, x0)
        path = prob.full_ee_path(scenes, xs, phase_scenes2, batch_index=0)
        return jnp.mean(jnp.sum((path - demo_path) ** 2, axis=-1))

    z_star = jnp.concatenate([THETA_IK_STAR, Z_TRAJOPT_STAR])
    z0 = jnp.concatenate([jnp.zeros(pp.K_IK, dtype=jnp.float32), jnp.zeros(pp.K_TRAJOPT, dtype=jnp.float32)])
    assert float(loss(z_star)) < 1e-9, "sanity check failed: loss at theta_star should be exactly 0"

    results = {}

    # -- implicit: warm the jit cache with ONE throwaway call, THEN time --
    gf = jax.jit(jax.value_and_grad(loss))
    t0 = time.perf_counter()
    jax.block_until_ready(gf(z0))
    compile_time_imp = time.perf_counter() - t0

    t0 = time.perf_counter()
    z_imp, _ = outer_opt.adam(gf, z0, lr=0.05, n_steps=n_steps_implicit)
    steady_time_imp = time.perf_counter() - t0

    theta_ik_imp, z_trajopt_imp = _unpack_z(z_imp)
    theta_trajopt_imp = jax.nn.softmax(z_trajopt_imp)
    param_err_imp = float(jnp.linalg.norm(
        jnp.concatenate([theta_ik_imp, theta_trajopt_imp]) -
        jnp.concatenate([THETA_IK_STAR, theta_trajopt_star])))
    rmse_imp = float(jnp.sqrt(loss(z_imp)))
    results["implicit"] = dict(
        param_err=param_err_imp, ee_rmse=rmse_imp, solves=n_steps_implicit,
        compile_s=compile_time_imp, steady_s=steady_time_imp,
        per_unit_s=steady_time_imp / n_steps_implicit,
        theta_ik_hat=np.asarray(theta_ik_imp), theta_trajopt_hat=np.asarray(theta_trajopt_imp),
    )

    # -- cmaes: same warm-then-time protocol --
    loss_j = jax.jit(loss)
    t0 = time.perf_counter()
    jax.block_until_ready(loss_j(z0))
    compile_time_cma = time.perf_counter() - t0

    lam = 4 + int(3 * np.log(z0.shape[0]))
    t0 = time.perf_counter()
    z_cma, _ = outer_opt.cma_es(loss_j, z0, n_gens=n_gens_cmaes, sigma0=0.3, seed=seed)
    steady_time_cma = time.perf_counter() - t0

    theta_ik_cma, z_trajopt_cma = _unpack_z(z_cma)
    theta_trajopt_cma = jax.nn.softmax(z_trajopt_cma)
    param_err_cma = float(jnp.linalg.norm(
        jnp.concatenate([theta_ik_cma, theta_trajopt_cma]) -
        jnp.concatenate([THETA_IK_STAR, theta_trajopt_star])))
    rmse_cma = float(jnp.sqrt(loss(z_cma)))
    n_solves_cma = n_gens_cmaes * lam
    results["cmaes"] = dict(
        param_err=param_err_cma, ee_rmse=rmse_cma, solves=n_solves_cma,
        compile_s=compile_time_cma, steady_s=steady_time_cma,
        per_unit_s=steady_time_cma / n_solves_cma,
        theta_ik_hat=np.asarray(theta_ik_cma), theta_trajopt_hat=np.asarray(theta_trajopt_cma),
    )
    return results


def _print_table(results):
    print(f"theta_ik_star = {np.asarray(THETA_IK_STAR)}")
    print(f"theta_trajopt_star = {np.asarray(jax.nn.softmax(Z_TRAJOPT_STAR))}")
    print()
    print(f"{'method':10s} {'param_err':>10s} {'ee_rmse':>10s} {'solves':>7s} "
          f"{'compile_s':>10s} {'steady_s':>10s} {'per_solve_s':>12s}")
    for name, r in results.items():
        print(f"{name:10s} {r['param_err']:10.4f} {r['ee_rmse']:10.4f} {r['solves']:7d} "
              f"{r['compile_s']:10.1f} {r['steady_s']:10.1f} {r['per_unit_s']:12.3f}")
    imp, cma = results["implicit"], results["cmaes"]
    print()
    print(f"solves ratio (cmaes/implicit): {cma['solves']/imp['solves']:.1f}x")
    print(f"steady-state wall ratio (cmaes/implicit): {cma['steady_s']/imp['steady_s']:.2f}x")


def sample_pickplace_scenes(rng, n, jitter_pos=0.03, jitter_q=0.05):
    """Sample `n` pick-and-place contexts by jittering the nominal scene.

    Mirrors `ioc.robot.problem.RobotProblem.sample_scenes`'s SPIRIT (small,
    per-context jitter around a nominal configuration, so recovery is measured
    across genuinely different contexts rather than one pinned scene) rather
    than reusing its code directly: `PickPlaceScene`'s fields (pick/place EE
    positions plus a start config) don't match `Scene`'s (paired joint-space
    start/goal), so there is no single function to share -- the jitter
    magnitudes (~3cm on the pick/place targets, ~0.05 rad on q_start) are
    chosen to be large enough to make each context a genuinely different IK/
    trajopt problem without moving the pick/place points outside the arm's
    reach or through the fixed obstacle.
    """
    starts, picks, places = [], [], []
    for _ in range(n):
        starts.append(np.asarray(Q_START) + rng.normal(scale=jitter_q, size=Q_START.shape[0]))
        picks.append(np.asarray(PICK_POS) + rng.normal(scale=jitter_pos, size=3))
        places.append(np.asarray(PLACE_POS) + rng.normal(scale=jitter_pos, size=3))
    return pp.PickPlaceScene(
        q_start=jnp.asarray(np.stack(starts), dtype=jnp.float32),
        pick_pos=jnp.asarray(np.stack(picks), dtype=jnp.float32),
        place_pos=jnp.asarray(np.stack(places), dtype=jnp.float32),
        obs_center=jnp.asarray(np.tile(np.asarray(OBS_CENTER), (n, 1)), dtype=jnp.float32),
        obs_radius=jnp.asarray(np.tile(np.asarray(OBS_RADIUS), (n, 1)), dtype=jnp.float32),
    )


def sweep_demo_count(demo_counts=(1, 2, 4, 8), n_steps=8, seed=0):
    """Recovery error vs number of demonstrations, implicit-only (paper-figure
    deliverable: does more demonstration data tighten recovery, the way it
    does for the single-segment study in `ioc.robot.e1_identifiability`?).

    Same `THETA_IK_STAR`/`Z_TRAJOPT_STAR` ground truth as `run()` above, now
    applied across `max(demo_counts)` independently-sampled contexts
    (`sample_pickplace_scenes`).  CMA-ES is skipped here -- its per-generation
    population cost (`lambda(K=9) = 10` solves/generation) makes a 4-point
    sweep prohibitively slow on top of `run()`'s own cost, and the sweep's
    question (does implicit's recovery improve with more data) doesn't need a
    CMA-ES reference to answer.

    Timing trick, load-bearing for tractability: recompiling the jitted loss
    for every distinct batch size (measured ~20+ minutes per shape in `run()`)
    would make a naive N in {1,2,4,8} sweep cost over an hour in compile alone.
    Instead this ALWAYS batches at `N_MAX = max(demo_counts)`, compiles ONCE,
    and selects which of the N_MAX demos are "active" for a given N via a
    0/1 `mask` passed into the (already-compiled) loss -- changing a runtime
    value, not a shape, so every N after the first reuses the same compiled
    executable.  The N_MAX-N inactive slots still get solved (wasted compute,
    traded for avoiding N_MAX-1 extra ~20-minute recompiles) but contribute
    zero to the masked loss/gradient.
    """
    N_MAX = max(demo_counts)
    prob = pp.PickPlaceProblem.load(str(URDF_PATH), str(SRDF_PATH), str(MESH_DIR))
    forward_solver = pp.make_composed_forward_solver(n_iters=60)
    rng = np.random.default_rng(seed)

    scenes = sample_pickplace_scenes(rng, N_MAX)
    theta_trajopt_star = jax.nn.softmax(Z_TRAJOPT_STAR)
    x0_star, phase_scenes_star, _, _ = prob.seeds(scenes, THETA_IK_STAR)

    inner_by_phase = {}
    for p in pp.PHASES:
        residual_fn, _ = prob.make_segment_inner(p, forward_solver)
        scales = prob.calibrate_segment(p, residual_fn, phase_scenes_star[p], jax.random.PRNGKey(seed))
        inner_by_phase[p] = make_inner_solver(residual_fn, scales, forward_solver=forward_solver)

    _, _, xs_gt, phase_scenes_gt = prob.solve(
        THETA_IK_STAR, _split_trajopt(theta_trajopt_star), scenes, inner_by_phase, x0_star)
    demo_paths = jnp.stack(
        [prob.full_ee_path(scenes, xs_gt, phase_scenes_gt, batch_index=i) for i in range(N_MAX)])

    def loss_masked(z, mask):
        theta_ik, z_trajopt = _unpack_z(z)
        theta_trajopt_by_phase = _split_trajopt(jax.nn.softmax(z_trajopt))
        x0, phase_scenes, _, _ = prob.seeds(scenes, theta_ik)
        _, _, xs, phase_scenes2 = prob.solve(theta_ik, theta_trajopt_by_phase, scenes, inner_by_phase, x0)
        paths = jnp.stack([prob.full_ee_path(scenes, xs, phase_scenes2, batch_index=i) for i in range(N_MAX)])
        per_demo_mse = jnp.mean(jnp.sum((paths - demo_paths) ** 2, axis=-1), axis=-1)
        return jnp.sum(per_demo_mse * mask) / jnp.sum(mask)

    z0 = jnp.concatenate([jnp.zeros(pp.K_IK, dtype=jnp.float32), jnp.zeros(pp.K_TRAJOPT, dtype=jnp.float32)])
    gf = jax.jit(jax.value_and_grad(loss_masked))

    t0 = time.perf_counter()
    jax.block_until_ready(gf(z0, jnp.ones(N_MAX, dtype=jnp.float32)))
    compile_time = time.perf_counter() - t0

    theta_star_vec = jnp.concatenate([THETA_IK_STAR, theta_trajopt_star])
    results = {}
    for N in demo_counts:
        mask = jnp.asarray(np.array([1.0] * N + [0.0] * (N_MAX - N), dtype=np.float32))
        t0 = time.perf_counter()
        z_hat, _ = outer_opt.adam(lambda z: gf(z, mask), z0, lr=0.05, n_steps=n_steps)
        wall = time.perf_counter() - t0
        theta_ik_hat, z_trajopt_hat = _unpack_z(z_hat)
        theta_trajopt_hat = jax.nn.softmax(z_trajopt_hat)
        param_err = float(jnp.linalg.norm(
            jnp.concatenate([theta_ik_hat, theta_trajopt_hat]) - theta_star_vec))
        ee_rmse = float(jnp.sqrt(loss_masked(z_hat, mask)))
        results[N] = dict(param_err=param_err, ee_rmse=ee_rmse, wall_s=wall)
    return results, compile_time


def _print_sweep_table(results, compile_time):
    print(f"one-time compile (batch={max(results)}): {compile_time:.1f}s")
    print(f"{'N demos':>8s} {'param_err':>10s} {'ee_rmse':>10s} {'wall_s':>8s}")
    for N, r in sorted(results.items()):
        print(f"{N:8d} {r['param_err']:10.4f} {r['ee_rmse']:10.4f} {r['wall_s']:8.1f}")


if __name__ == "__main__":
    _print_table(run())
