"""Generate the E10 method-comparison LaTeX table from summary.json.

Columns: reconstruction error vs the demonstrated joint trajectory (fit/held-out,
in rad), end-effector error (fit/held-out, in m), final outer loss, wall-clock
time (compile + inference), and the identified cost rank (Gram-spectrum rank).

Usage:
    python -m iosp.analysis.make_e10_table \
        [--summary iosp/data/results/e10_methods/summary.json] \
        [--out iosp/figures/e10_method_comparison.tex]
"""
import argparse
import json
import math
import pathlib

# method key -> pretty label
LABELS = {
    "random": "Random weights",
    "implicit": "Implicit diff.",
    "fd": "Finite diff.",
    "cmaes": "CMA-ES",
    "unrolled": "Unrolled",
}
ORDER = ["random", "implicit", "fd", "cmaes", "unrolled"]


def _fmt(x, prec=3):
    if x is None:
        return "--"
    try:
        xf = float(x)
    except (TypeError, ValueError):
        return "--"
    if not math.isfinite(xf):
        return r"$\infty$"
    return f"{xf:.{prec}f}"


def _fmt_time(s):
    if s is None or not math.isfinite(float(s)):
        return "--"
    s = float(s)
    if s < 60:
        return f"{s:.0f}"
    return f"{s/60:.1f}"


def main():
    ap = argparse.ArgumentParser()
    here = pathlib.Path(__file__).resolve().parents[1]
    ap.add_argument("--summary", type=str,
                    default=str(here / "data" / "results" / "e10_methods" / "summary.json"))
    ap.add_argument("--out", type=str,
                    default=str(here / "figures" / "e10_method_comparison.tex"))
    args = ap.parse_args()

    with open(args.summary) as f:
        S = json.load(f)

    init = S["init_metrics"]
    methods = S["methods"]

    # Assemble rows: (label, jfit, jgen, eefit, eegen, loss, time_min, rank)
    rows = []
    for key in ORDER:
        if key == "random":
            m = init
            rows.append((LABELS[key],
                         m["joint_rmse_fit"], m["joint_rmse_gen"],
                         m["ee_rmse_fit"], m["ee_rmse_gen"], m["loss"],
                         None, None))
            continue
        if key not in methods:
            continue
        r = methods[key]
        m = r.get("metrics", {})
        gram = r.get("gram") or {}
        t_total = r.get("wall_total_s")
        rows.append((LABELS[key],
                     m.get("joint_rmse_fit"), m.get("joint_rmse_gen"),
                     m.get("ee_rmse_fit"), m.get("ee_rmse_gen"), m.get("loss"),
                     t_total, gram.get("rank")))

    n_fit = S.get("n_fit")
    K = S.get("K")

    lines = []
    lines.append("% Auto-generated by iosp/analysis/make_e10_table.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{5pt}")
    lines.append(r"\begin{tabular}{lcccccc}")
    lines.append(r"\toprule")
    lines.append(r"& \multicolumn{2}{c}{Joint RMSE (rad)} "
                 r"& \multicolumn{2}{c}{EE RMSE (m)} & & \\")
    lines.append(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}")
    lines.append(r"Method & Fit & Held-out & Fit & Held-out "
                 r"& Loss & Time (min) \\")
    lines.append(r"\midrule")
    for (label, jf, jg, ef, eg, loss, t, rank) in rows:
        lines.append(
            f"{label} & {_fmt(jf)} & {_fmt(jg)} & {_fmt(ef)} & {_fmt(eg)} "
            f"& {_fmt(loss)} & {_fmt_time(t)} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    cap = (r"\caption{Inverse-cost recovery on the FR3 human teleoperation "
           f"episodes ({n_fit} fit / held-out split, ${K}$ cost weights). "
           r"Reconstruction error is the RMSE of the fitted trajectory-optimiser "
           r"rollout against the demonstrated joint trajectory; the end-effector "
           r"RMSE is reported from the same rollout. `Random weights' is the "
           r"$u=0$ prior. Time is total wall clock (compile + inference).}")
    lines.append(cap)
    lines.append(r"\label{tab:e10_methods}")
    lines.append(r"\end{table}")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
