"""Cross-domain aggregate table — pick-place, tetris, block stacking.

One row per (domain, difficulty level), aggregated over seeds.  The metric
set is behavioural first, per this codebase's convention: held-out EE RMSE
of the recovered cost, the uniform-theta baseline it must beat, the oracle
theta* floor, and the normalised regret

    regret = (fit - oracle) / (baseline - oracle)

which is 0 for a perfect recovery and 1 for no better than uniform.  Raw
`param_err` is reported last and explicitly labelled as context, not as the
criterion -- along near-null eigendirections it is uninformative (see
`iosp.viz.fig_eigenspectrum`).

Schema adapters: tetris/tower write `.npz` from `e8_tetris`/`e9_tower`;
pick-place writes `.json` from `e4_three_stage`.  Both already carry
`baseline*`/`fit.test_rmse`/`oracle`/`param_err`, so no experiment change is
needed -- only the load path differs.

    python -m iosp.analysis.table_domains iosp/data/results/
    python -m iosp.analysis.table_domains iosp/data/results/ --out table_domains.tex
"""

import argparse
import glob
import json
import os
import re

import numpy as np

# (domain label, results subdir, level-arg name shown in the table)
DOMAINS = [
    ("Pick-place", "pickplace", None),
    ("Tetris packing", "tetris", "blocks"),
    ("Block stacking", "tower", "blocks"),
]


def _seed_from_path(path):
    m = re.search(r"seed(\d+)", os.path.basename(path))
    return int(m.group(1)) if m else 0


def _level_from_path(path):
    m = re.search(r"blocks(\d+)", os.path.basename(path))
    return int(m.group(1)) if m else None


def _record(baseline, fit, oracle, param_err, seed, level):
    denom = baseline - oracle
    regret = float((fit - oracle) / denom) if denom > 1e-12 else float("nan")
    return dict(baseline=float(baseline), fit=float(fit), oracle=float(oracle),
                regret=regret, param_err=float(param_err),
                seed=seed, level=level)


def _load_npz(path):
    """e8_tetris / e9_tower schema."""
    d = np.load(path, allow_pickle=True)
    if "baseline" not in d or "test_rmse" not in d:
        return None
    return _record(float(d["baseline"]), float(d["test_rmse"]),
                   float(d["oracle"]), float(d["param_err"]),
                   _seed_from_path(path), _level_from_path(path))


def _load_json(path):
    """e4_three_stage schema."""
    with open(path) as f:
        d = json.load(f)
    base = d.get("baseline_uniform", d.get("baseline_zero"))
    if base is None or "fit" not in d:
        return None
    return _record(base, d["fit"]["test_rmse"], d["oracle"], d["param_err"],
                   _seed_from_path(path), _level_from_path(path))


def _load_domain(results_root, subdir):
    rows = []
    ddir = os.path.join(results_root, subdir)
    for path in sorted(glob.glob(os.path.join(ddir, "*.npz"))
                       + glob.glob(os.path.join(ddir, "*.json"))):
        if path.endswith(".manifest.json"):
            continue
        try:
            r = _load_json(path) if path.endswith(".json") else _load_npz(path)
        except Exception as e:                      # noqa: BLE001
            print(f"[table_domains] skip {path}: {e}")
            continue
        if r is not None:
            rows.append(r)
    return rows


def _agg(rows, key):
    v = np.array([r[key] for r in rows], float)
    v = v[np.isfinite(v)]
    if v.size == 0:
        return float("nan"), float("nan")
    return float(v.mean()), float(v.std())


def _fmt(mean, std, prec=3, bold=False):
    if not np.isfinite(mean):
        return "--"
    body = rf"{mean:.{prec}f} \pm {std:.{prec}f}"
    # keep the \pm inside math mode -- \textbf{$...$}, never $\textbf{...}$
    return rf"$\mathbf{{{body}}}$" if bold else f"${body}$"


def render(input_path, out_path):
    """input_path: iosp/data/results/ root.  out_path: .tex file."""
    groups = []   # (domain label, level label, rows)
    for label, subdir, level_name in DOMAINS:
        rows = _load_domain(input_path, subdir)
        if not rows:
            print(f"[table_domains] no results for {label} ({subdir}/)")
            continue
        levels = sorted({r["level"] for r in rows},
                        key=lambda x: (x is None, x))
        for lv in levels:
            sub = [r for r in rows if r["level"] == lv]
            lv_label = "--" if lv is None else f"{lv} {level_name}"
            groups.append((label, lv_label, sub))

    if not groups:
        raise FileNotFoundError(
            f"no domain results under {input_path} "
            f"(expected {'/, '.join(d[1] for d in DOMAINS)}/)")

    lines = [
        r"% generated by iosp.analysis.table_domains -- do not edit by hand",
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"Domain & Scene & $n$ & Uniform & \textbf{IOSP} & Oracle "
        r"& Regret & $\|\Delta\theta\|$ \\",
        r" &  &  & \multicolumn{3}{c}{held-out EE RMSE (m)} & (norm.) "
        r"& (context) \\",
        r"\midrule",
    ]

    prev_label = None
    for label, lv_label, rows in groups:
        shown = "" if label == prev_label else label
        prev_label = label
        n = len(rows)
        cells = [
            _fmt(*_agg(rows, "baseline")),
            _fmt(*_agg(rows, "fit"), bold=True),
            _fmt(*_agg(rows, "oracle")),
            _fmt(*_agg(rows, "regret")),
            _fmt(*_agg(rows, "param_err")),
        ]
        lines.append(f"{shown} & {lv_label} & {n} & " + " & ".join(cells)
                     + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}"]
    tex = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write(tex)
    print(f"[table_domains] {len(groups)} row(s) -> {out_path}")

    # human-readable echo, so a run is checkable without compiling LaTeX
    print(f"\n{'domain':16s} {'scene':12s} {'n':>2s} {'uniform':>9s} "
          f"{'iosp':>9s} {'oracle':>9s} {'regret':>8s}")
    for label, lv_label, rows in groups:
        print(f"{label:16s} {lv_label:12s} {len(rows):>2d} "
              f"{_agg(rows,'baseline')[0]:>9.5f} {_agg(rows,'fit')[0]:>9.5f} "
              f"{_agg(rows,'oracle')[0]:>9.5f} {_agg(rows,'regret')[0]:>8.3f}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("input", nargs="?", default="iosp/data/results/")
    ap.add_argument("--out", default="iosp/figures/table_domains.tex")
    a = ap.parse_args()
    render(a.input, a.out)
