"""GRiD CUDA-kernel dynamics backend for spasm-pyroffi (opt-in).

pyroffi ships a `pyroffi.dynamics.GRiDDynamics` path: per-robot CUDA kernels
JIT-generated by GRiDCodeGenerator (RNEA/CRBA + **analytic-gradient** kernels)
and registered through the JAX FFI. This module wraps it as an alternative to
the pure-JAX dynamics used in `extensions/dynamics.py`, sharing the same
`DYN_ROBOT` (pyroffi's inertial-complete, mimic-free `panda_spherized.urdf`).

Correctness (see tests): GRiD is **fully vmap-safe and batch-correct**.
`GRiDDynamics` wraps each raw kernel with `jax.custom_batching.custom_vmap`
(`_batchable` in pyroffi's `_grid_dynamics.py`): a `jax.vmap` folds the mapped
axis in as one more *leading batch dimension* and issues a **single fused
kernel launch** (not a batch-of-batches, not a Python loop). We verified this
empirically -- GRiD single-point vs GRiD `lax.scan` vs GRiD `jax.vmap` vs GRiD
native leading-batch are **bit-identical (maxdiff 0.0)** for both the forward
pass and the gradient, and all match pure-JAX autodiff to ~3e-7 relative. So
GRiD's forward and analytic gradient can be used directly in batched,
differentiable code (e.g. a trajopt cost over T waypoints).

  * `inverse_dynamics_grid` -- forward, vmap-safe.
  * `torque_profile_grid`   -- vmapped analogue of `dynamics.torque_profile`.
  * `torque_cost_grid`      -- differentiable, drop-in for `dynamics.torque_cost`
                               (analytic-gradient kernel instead of autodiff).

(Historical note: an earlier version of this file claimed a GRiD "batching bug"
after seeing ~0.05 Nm / ~1e3 gradient drift *versus pure-JAX vmap*. That drift
is entirely on the pure-JAX side: JAX's own `vmap` reorders f32 reductions
differently from a JAX loop, and on a sum-of-squares loss with ~1e6-scale
gradients that shows up as large *absolute* maxdiff (~1e-3 relative). GRiD is
self-consistent to the bit; the "bug" was a bad reference choice. Retracted.)

Speed, honestly, is the reason this is still opt-in rather than the default. On
the 7-DOF Panda at SPaSM's sizes GRiD's per-launch overhead makes it a
wash-to-slower: forward inverse dynamics ~0.5 ms (JAX) vs ~0.7 ms (GRiD) at
batch 256; a T=70 trajectory *gradient* is ~0.71 ms (JAX) vs ~1.03 ms (GRiD).
GRiD only edges JAX out on the gradient at larger batch (B~256: 0.56 vs
0.75 ms), where the analytic-gradient kernel amortizes its launch cost. So the
pure-JAX path in `extensions/dynamics.py` stays the default for SPaSM's
trajectory-scale work; GRiD is the right tool for big-DOF arms / large-batch
MPC where the analytic-gradient kernel wins -- included as that capability,
correct and honestly benchmarked, not as a free speedup at 7 DOF (the same
verdict the report reached for the CUDA FK kernel, REPORT.md sec 4.2).
"""
import os
import sys

import jax
import jax.numpy as jnp
import pyroffi as pk


import spasm.extensions.dynamics as dyn  # noqa: E402  (DYN_ROBOT, TORQUE_LIMITS, casts)

_GRID = None


def get_grid():
    """Lazily build (and cache) the GRiDDynamics for DYN_ROBOT.

    The first call JIT-generates + compiles the per-robot CUDA kernels
    (~1-2 s, needs `sympy` for codegen); subsequent calls are free. Kept out of
    import so `extensions.dynamics` stays importable without CUDA/sympy."""
    global _GRID
    if _GRID is None:
        _GRID = pk.dynamics.GRiDDynamics.from_robot(dyn.DYN_ROBOT)
    return _GRID


def inverse_dynamics_grid(q, qd, qdd):
    """tau via the GRiD CUDA kernel; accepts arbitrary leading batch dims and
    is vmap-safe (a `jax.vmap` becomes one fused launch). f32 in / f32 out."""
    q, qd, qdd = dyn._cast_f32(q, qd, qdd)
    tau = get_grid().inverse_dynamics(q, qd, qdd)
    return jnp.asarray(tau, dtype=jnp.float32)


def torque_profile_grid(q_traj, dt):
    """GRiD-backed analogue of `extensions.dynamics.torque_profile`. Same dict
    output; uses one fused GRiD launch over the T waypoints (`jax.vmap`)."""
    q_traj = jnp.asarray(q_traj, dtype=jnp.float32)
    dt = float(dt)
    qd, qdd = dyn._finite_diff_qd_qdd(q_traj, dt)

    tau = jax.vmap(inverse_dynamics_grid)(q_traj, qd, qdd)   # (T, 7), single launch
    max_abs_tau = jnp.max(jnp.abs(tau), axis=0)
    return {
        'tau': tau,
        'qd': qd,
        'qdd': qdd,
        'max_abs_tau': max_abs_tau,
        'limit_violation': max_abs_tau > dyn.TORQUE_LIMITS,
        'violation_frac': jnp.maximum(
            0.0, (jnp.abs(tau) - dyn.TORQUE_LIMITS[None, :]) / dyn.TORQUE_LIMITS[None, :]),
    }


def torque_cost_grid(q_traj, dt):
    """Differentiable soft torque-limit penalty, drop-in for
    `extensions.dynamics.torque_cost` but with torques (and their gradient)
    from GRiD's analytic-gradient CUDA kernel instead of pure-JAX autodiff.
    vmap-safe and correct; provided for the big-DOF/large-batch regime where
    GRiD's analytic gradient beats autodiff (see module docstring for the 7-DOF
    speed caveat)."""
    q_traj = jnp.asarray(q_traj, dtype=jnp.float32)
    dt = float(dt)
    qd, qdd = dyn._finite_diff_qd_qdd(q_traj, dt)
    tau = jax.vmap(inverse_dynamics_grid)(q_traj, qd, qdd)
    over = jax.nn.relu(jnp.abs(tau) - dyn.TORQUE_LIMITS[None, :])
    return jnp.sum(over ** 2)


def benchmark(batch_sizes=(256, 4096), seed=0):
    """Honest pure-JAX vs GRiD comparison (forward + gradient). Correctness is
    reported against a *JAX single-point loop* (the reduction-order-stable
    reference), NOT against pure-JAX vmap. Returns the results dict."""
    import time
    gd = get_grid()
    out = {}

    def _t(f, *a, n=50):
        f(*a).block_until_ready()
        t = time.perf_counter()
        for _ in range(n):
            r = f(*a)
        r.block_until_ready()
        return 1000 * (time.perf_counter() - t) / n

    for B in batch_sizes:
        k = jax.random.split(jax.random.key(seed), 3)
        Q = jax.random.normal(k[0], (B, 7)) * 0.3
        QD = jax.random.normal(k[1], (B, 7)) * 0.2
        QDD = jax.random.normal(k[2], (B, 7)) * 0.5

        # correctness vs a JAX single-point loop (stable reference)
        jl = jnp.stack([dyn.DYN_ROBOT.inverse_dynamics(Q[i], QD[i], QDD[i]) for i in range(min(B, 64))])
        gl = jax.vmap(gd.inverse_dynamics)(Q, QD, QDD)[:min(B, 64)]
        rel = float(jnp.max(jnp.abs(gl - jl)) / jnp.max(jnp.abs(jl)))

        fj = jax.jit(jax.vmap(dyn.DYN_ROBOT.inverse_dynamics))
        fg = jax.jit(lambda q, qd, qdd: gd.inverse_dynamics(q, qd, qdd))
        gj = jax.jit(jax.grad(lambda Q: jnp.sum(jax.vmap(dyn.DYN_ROBOT.inverse_dynamics)(Q, QD, QDD) ** 2)))
        gg = jax.jit(jax.grad(lambda Q: jnp.sum(jax.vmap(gd.inverse_dynamics)(Q, QD, QDD) ** 2)))

        rec = {
            'fwd_rel_vs_jaxloop': rel,
            'fwd_jax_ms': _t(fj, Q, QD, QDD),
            'fwd_grid_ms': _t(fg, Q, QD, QDD),
            'grad_jax_ms': _t(gj, Q),
            'grad_grid_ms': _t(gg, Q),
        }
        out[f'batch_{B}'] = rec
        print(f"B={B}: fwd rel-err vs JAX-loop {rec['fwd_rel_vs_jaxloop']:.1e} | "
              f"fwd jax {rec['fwd_jax_ms']:.3f} grid {rec['fwd_grid_ms']:.3f} ms | "
              f"grad jax {rec['grad_jax_ms']:.3f} grid {rec['grad_grid_ms']:.3f} ms")
    return out


if __name__ == '__main__':
    benchmark()
