"""CPU-accelerated end-effector forward kinematics via VAMP, JIT-compiled per robot.

This is the FK counterpart to :class:`pyroffi.collision.VAMPCPUCollisionChecker`,
and is built on the same cricket codegen + JIT + XLA-FFI machinery: cricket
parses the URDF and emits a ``vamp::robots::<Robot>`` struct whose straight-line
``eefk`` kernel is stitched into a tiny translation unit (``_robot_fk_tu.cc.in``
+ ``_fk_ffi.hh``), JIT-compiled once (object-cached on disk), and registered as
an XLA FFI custom call for ``platform="cpu"``.

VAMP's ``eefk`` returns the **end-effector** world pose only (its FK is
specialised to the collision end-effector at codegen time), so this exposes a
batched ``[B, 4, 4]`` end-effector FK rather than pyroffi's full per-link pose
stack.  It is intended for CPU-only accelerated planning (``JAX_PLATFORMS=cpu``):
paired with :class:`VAMPCPUCollisionChecker` and a QuIK / JAX-Halley IK solver it
gives a fast all-CPU kinematics + planning stack for simple serial arms.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Optional

import jax
import jax.numpy as jnp
import numpy as np
from jax import Array
from jaxtyping import Float

from .._jit_ffi import (
    cpu_device,
    cricket_jit,
    eigen_include_dirs,
    register_handlers,
    xla_ffi_include,
)

_KERNELS_DIR = Path(__file__).resolve().parent.parent / "vamp_kernels"
_FFI_HEADER = _KERNELS_DIR / "_fk_ffi.hh"
_TU_TEMPLATE = _KERNELS_DIR / "_robot_fk_tu.cc.in"
_REPO_ROOT = Path(__file__).resolve().parents[3]
_DEFAULT_VAMP_INCLUDE = _REPO_ROOT / "external" / "vamp" / "src" / "impl"


def _robot_name_from_urdf(urdf_path: Path) -> str:
    """Reuse the collision backend's URDF -> C++ struct name derivation."""
    from ..collision._vamp_collision import _robot_name_from_urdf as _n

    return _n(urdf_path)


class VAMPCPUForwardKinematics:
    """JIT-compiled VAMP end-effector FK for a concrete robot.

    Args mirror :class:`VAMPCPUCollisionChecker` (cricket needs the URDF/SRDF and
    end-effector, not a pyroffi model).
    """

    @classmethod
    def from_robot(
        cls,
        robot,
        urdf_path: str | Path,
        srdf_path: Optional[str | Path] = None,
        end_effector: Optional[str] = None,
        **kwargs,
    ) -> "VAMPCPUForwardKinematics":
        """Build the VAMP CPU FK backend for ``robot``.

        The unified ``from_robot`` entry point shared by the external-binding
        backends (see :mod:`pyroffi.bindings`).  **File-path exception:** unlike
        GRiD/QuIK, VAMP's kernel is generated by cricket directly from the URDF
        (and SRDF) *files* rather than pyroffi's in-memory model, so the source
        ``urdf_path`` (and optional ``srdf_path``) must be passed explicitly;
        ``robot`` is accepted only for call-site symmetry.
        """
        return cls(
            urdf_path, srdf_path=srdf_path, end_effector=end_effector, **kwargs
        )

    def __init__(
        self,
        urdf_path: str | Path,
        srdf_path: Optional[str | Path] = None,
        end_effector: Optional[str] = None,
        *,
        robot_name: Optional[str] = None,
        resolution: int = 32,
        cache_dir: Optional[str | Path] = None,
        include_dirs: Optional[list[str]] = None,
        extra_flags: Optional[list[str]] = None,
    ) -> None:
        cricket, jit = cricket_jit()
        urdf_path = Path(urdf_path).resolve()
        srdf_path = Path(srdf_path).resolve() if srdf_path is not None else None
        if robot_name is None:
            robot_name = _robot_name_from_urdf(urdf_path)

        gen = cricket.generate_robot_source(
            cricket.GenOptions(
                urdf=urdf_path,
                srdf=srdf_path,
                end_effector=end_effector,
                data={"name": robot_name, "resolution": int(resolution)},
            )
        )
        robot_type_name = gen.robot_name
        robot_token = robot_type_name.lower()
        self._dimension = int(gen.dimension)

        digest = hashlib.sha1()
        digest.update(gen.source.encode())
        digest.update(_FFI_HEADER.read_bytes())
        digest.update(_TU_TEMPLATE.read_bytes())
        src_hash = digest.hexdigest()[:16]
        work_dir = Path(cache_dir) if cache_dir is not None else Path(jit.default_cache_dir())
        work_dir.mkdir(parents=True, exist_ok=True)
        header_path = work_dir / f"vamp_robot_{robot_token}_{src_hash}.hh"
        if not header_path.exists():
            header_path.write_text(gen.source)

        tu_source = (
            _TU_TEMPLATE.read_text()
            .replace("@ROBOT_HEADER@", str(header_path))
            .replace("@FFI_HEADER@", str(_FFI_HEADER))
            .replace("@ROBOT_TYPE@", f"vamp::robots::{robot_type_name}")
            .replace("@ROBOT_NAME@", robot_token)
        )

        opts = jit.CompileOptions()
        opts.std_flag = "-std=c++17"
        opts.opt_flag = "-O3"
        dirs = [str(_DEFAULT_VAMP_INCLUDE), xla_ffi_include(), *eigen_include_dirs()]
        if include_dirs:
            dirs.extend(include_dirs)
        # The cricket-generated robot header transitively includes VAMP's CAPT
        # environment (pdqsort), so add its fetched-dep dir like the collision
        # backend does.
        from ..collision._vamp_collision import _find_pdqsort_dir

        pdq = _find_pdqsort_dir()
        if pdq:
            dirs.append(pdq)
        opts.include_dirs = dirs
        opts.extra_flags = extra_flags or ["-march=native", "-fopenmp"]
        opts.module_id = f"vamp_fk_{robot_token}_{src_hash}"

        self._target = f"vamp_eefk_{robot_token}_{src_hash}"
        register_handlers(
            tu_source, opts, work_dir, {self._target: "pyroffi_get_eefk"}
        )
        self._jit_fn = None

    @property
    def dimension(self) -> int:
        return self._dimension

    def _fn(self):
        if self._jit_fn is None:
            target = self._target

            def impl(a):
                return jax.ffi.ffi_call(
                    target, jax.ShapeDtypeStruct((a.shape[0], 4, 4), jnp.float32)
                )(a)

            self._jit_fn = jax.jit(impl)
        return self._jit_fn

    def ee_poses(
        self, cfg: Float[Array, "*batch dim"]
    ) -> Float[Array, "*batch 4 4"]:
        """Batched world<-end-effector homogeneous transforms for ``cfg``."""
        cfg = jnp.asarray(cfg, jnp.float32)
        batch_axes = cfg.shape[:-1]
        d = cfg.shape[-1]
        B = int(np.prod(batch_axes)) if batch_axes else 1
        flat = jax.device_put(cfg.reshape(B, d), cpu_device())
        out = self._fn()(flat)
        return out.reshape(*batch_axes, 4, 4) if batch_axes else out.reshape(4, 4)


def make_vamp_cpu_fk(
    urdf_path: str | Path,
    srdf_path: Optional[str | Path] = None,
    end_effector: Optional[str] = None,
    **kwargs,
) -> VAMPCPUForwardKinematics:
    """Build a JIT-compiled VAMP CPU end-effector FK for ``urdf_path``."""
    return VAMPCPUForwardKinematics(
        urdf_path, srdf_path=srdf_path, end_effector=end_effector, **kwargs
    )
