"""LaTeX table for the KKT-seeding ablation (see `ioc.bench2d.run_kkt_seed`).

    python -m ioc.analysis.kkt_seed_table

Writes a booktabs-style IEEE T-RO table to `ioc/figures/table_kkt_seed.tex`
(not compiled -- meant to be \\input into the paper). One row per (bump width,
restarts, demonstration noise) cell; bolds whichever arm has the lower median
regret in that cell. Regret, not weight-space L1, is the header metric: it is
what the bilevel fit is actually scored against, and L1 error on a softmax
parameterization is not comparable across cells with different K.
"""

import json
import os
import re

import numpy as np
import tyro

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data", "bench2d")
FIGS = os.path.join(HERE, "..", "figures")


def _fmt(med, q1, q3, bold):
    s = f"{med:.2e}"
    if "e" in s:
        m, exp = s.split("e")
        s = f"{m}\\!\\times\\!10^{{{int(exp)}}}"
    s = f"${s}$"
    return f"\\textbf{{{s}}}" if bold else s


def main(results: str = "bench2d_kkt_seed_dynamics.json",
         out: str = "table_kkt_seed.tex"):
    path = results if os.path.isabs(results) or os.path.exists(results) \
        else os.path.join(DATA, results)
    if not os.path.exists(path):
        raise SystemExit(f"no such file: {path}")
    data = json.load(open(path))

    rows = []
    for tag, d in data.items():
        m = re.match(r"bw([\d.]+)_R(\d+)_sigma([\d.]+)", tag)
        bw, R, sigma = m.group(1), int(m.group(2)), float(m.group(3))
        res = d["results"]
        r_l1 = [t["arms"]["random"]["l1"] for t in res.values()]
        k_l1 = [t["arms"]["kkt_seed"]["l1"] for t in res.values()]
        r_rg = [t["arms"]["random"]["regret"] for t in res.values()]
        k_rg = [t["arms"]["kkt_seed"]["regret"] for t in res.values()]
        rows.append(dict(
            bw=bw, R=R, sigma=sigma, n=len(res),
            r_l1=np.median(r_l1), k_l1=np.median(k_l1),
            r_rg_med=np.median(r_rg), r_rg_q1=np.percentile(r_rg, 25), r_rg_q3=np.percentile(r_rg, 75),
            k_rg_med=np.median(k_rg), k_rg_q1=np.percentile(k_rg, 25), k_rg_q3=np.percentile(k_rg, 75),
        ))
    rows.sort(key=lambda r: (-float(r["bw"]), r["R"], r["sigma"]))

    lines = []
    lines.append(r"% Auto-generated by `python -m ioc.analysis.kkt_seed_table`. Not compiled here.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{KKT-seeding ablation on \texttt{field} (dynamics-routed): "
                 r"implicit-adjoint Adam fit from a random $z_0$ vs.\ from "
                 r"\texttt{analytic.kkt\_fit}'s solution, matched budget and contexts. "
                 r"Median cost regret over $n$ seeds (lower is better); bold marks the winner.}")
    lines.append(r"\label{tab:kkt_seed}")
    lines.append(r"\begin{tabular}{ll r r r}")
    lines.append(r"\toprule")
    lines.append(r"Regime & $R$ & $\sigma$ & Regret (random $z_0$) & Regret (KKT-seeded $z_0$) \\")
    lines.append(r"\midrule")

    last_regime = None
    for r in rows:
        regime = "wide (unimodal)" if r["bw"] == rows[0]["bw"] else "narrow (multimodal)"
        # rows are sorted with widest bw first; recompute regime from bw value
        # directly rather than position, since sort order and "first" can drift.
        regime = "wide (unimodal)" if float(r["bw"]) >= 0.7 else "narrow (multimodal)"
        if regime != last_regime:
            if last_regime is not None:
                lines.append(r"\addlinespace")
            last_regime = regime
        bold_r = r["r_rg_med"] < r["k_rg_med"]
        bold_k = not bold_r
        r_cell = _fmt(r["r_rg_med"], r["r_rg_q1"], r["r_rg_q3"], bold_r)
        k_cell = _fmt(r["k_rg_med"], r["k_rg_q1"], r["k_rg_q3"], bold_k)
        lines.append(f"{regime} & {r['R']} & {r['sigma']:.2f} & {r_cell} & {k_cell} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    os.makedirs(FIGS, exist_ok=True)
    out_path = os.path.join(FIGS, out)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}")

    n_kkt_wins = sum(1 for r in rows if r["k_rg_med"] < r["r_rg_med"])
    print(f"kkt_seed wins {n_kkt_wins}/{len(rows)} regimes on median regret")


if __name__ == "__main__":
    tyro.cli(main)
