"""E1: synthetic identifiability experiment for differentiable inverse optimal control.

Ground-truth cost weights are known.  Demonstrations are generated by solving a
kinematic reach-with-obstacle trajectory optimization under those weights; each
method must recover them from the demonstrated trajectories alone.

Inner problem (per context c, interior waypoints x = q_{1..T-2} free, endpoints fixed):

    x*(theta, c) = argmin_x  sum_k theta_k * phi_k(x, c),      theta in the simplex

Outer problem:

    min_z  L(z) = sum_i || p_ee(x*(softmax(z), c_i)) - p_ee(x_demo_i) ||^2

Methods compared:
  implicit   -- custom_vjp adjoint through the inner KKT point (1 solve / step)
  unrolled   -- reverse-mode through the inner Newton iterations
  fd         -- finite differences on L(z) (K+1 solves / step)
  cmaes      -- derivative-free search on z (population solves / step)
  kkt        -- feature-matching residual ||grad_x J_theta(x_demo)||^2 (0 solves)

Run under float64: the implicit adjoint needs an accurate inner Hessian.

    XLA_PYTHON_CLIENT_PREALLOCATE=false JAX_ENABLE_X64=1 CUDA_VISIBLE_DEVICES=0 \
        python examples/21_00_ioc_e1_synthetic.py
"""

import dataclasses
import functools
import json
import time

import jax
import jax.numpy as jnp
import numpy as np
import pyroffi as pk
import tyro
import yourdfpy

# ---------------------------------------------------------------------------
# Problem setup
# ---------------------------------------------------------------------------

N_TIMESTEPS = 24  # overridden by --n-timesteps
EE_LINK = "panda_hand"
CLEARANCE_MARGIN = 0.05  # [m] distance at which the collision feature turns on
SOFTMIN_TAU = 0.02  # [m] temperature of the soft-min over collision pairs
SOFTNESS = 60.0  # smoothing of the collision hinge; keeps the Hessian continuous

FEATURE_NAMES = ("effort", "collision", "smooth")
K = len(FEATURE_NAMES)


@jax.tree_util.register_dataclass
@dataclasses.dataclass(frozen=True)
class Scene:
    """A single demonstration context: fixed endpoints plus one spherical obstacle."""

    q_start: jnp.ndarray  # (dof,)
    q_goal: jnp.ndarray  # (dof,)
    obs_center: jnp.ndarray  # (3,)
    obs_radius: jnp.ndarray  # (1,)


def make_world(scene: Scene):
    return pk.collision.Sphere.from_center_and_radius(
        scene.obs_center[None, :], scene.obs_radius
    )


def unpack(x_flat, scene, dof):
    """Interior waypoints -> full trajectory with the endpoints clamped on."""
    interior = x_flat.reshape(N_TIMESTEPS - 2, dof)
    return jnp.concatenate(
        [scene.q_start[None, :], interior, scene.q_goal[None, :]], axis=0
    )


def residuals(x_flat, scene, robot, robot_coll, dof, collinear: bool):
    """Per-feature residual vectors r_k, with phi_k = ||r_k||^2.

    The features are expressed as residuals rather than scalars so the inner
    problem is a weighted nonlinear least-squares problem.  Its Gauss-Newton
    Hessian sum_k theta_k J_k^T J_k is positive semidefinite by construction,
    which is what makes x*(theta) a well-defined, locally smooth function of
    theta.  With a general (indefinite) Hessian the solver stalls in
    negative-curvature regions and the iterate it returns jumps discontinuously
    under infinitesimal changes of theta -- measured here at up to 0.3 rad of
    jump for a 1e-4 change in a weight, which destroys both finite differences
    and the implicit-function theorem.
    """
    q = unpack(x_flat, scene, dof)

    r_effort = (q[1:] - q[:-1]).reshape(-1)
    r_smooth = (q[2:] - 2.0 * q[1:-1] + q[:-2]).reshape(-1)

    # Sphere-level clearance, computed analytically rather than through
    # `compute_world_collision_distance`.  That helper reduces over the spheres
    # within each link with a hard max, and a hard max/min is nondifferentiable
    # exactly where the nearest sphere switches identity -- which is the ridge
    # the optimizer drives the solution onto.  The result is a cost that
    # converges while its gradient never vanishes: the solve stalls at a
    # non-stationary point (measured: only ~53% of scenes reached ||grad||<1e-5
    # even at 400 iterations), and both the implicit function theorem and finite
    # differences become invalid there.  Sphere-vs-sphere distance is smooth in
    # closed form, so every reduction here is a soft-min instead.
    coll = robot_coll.at_config(robot, q)  # (T, S, N) spheres
    centers = coll.pose.translation()  # (T, S, N, 3)
    radii = coll.radius  # (T, S, N)
    d = (
        jnp.linalg.norm(centers - scene.obs_center, axis=-1)
        - radii
        - scene.obs_radius[0]
    )
    d = d.reshape(d.shape[0], -1)  # (T, S*N)
    d_min = -SOFTMIN_TAU * jax.scipy.special.logsumexp(-d / SOFTMIN_TAU, axis=-1)
    r_coll = jax.nn.softplus(SOFTNESS * (CLEARANCE_MARGIN - d_min)) / SOFTNESS

    if collinear:
        # Deliberately near-degenerate control: a second copy of the velocity
        # residual.  Every method should fail to separate the two, and the
        # recovered weights should be flat along their difference.
        r_smooth = r_effort

    return (r_effort, r_coll, r_smooth)


def features(x_flat, scene, robot, robot_coll, dof, collinear: bool):
    """phi(x, c) in R^K, whitened by fixed nominal scales set in `calibrate_scales`."""
    rs = residuals(x_flat, scene, robot, robot_coll, dof, collinear)
    return jnp.stack([jnp.sum(r**2) for r in rs])


def ee_positions(q, robot, ee_index):
    return robot.forward_kinematics(q)[..., ee_index, 4:7]


# ---------------------------------------------------------------------------
# Inner solver: damped Newton with a fixed iteration count
# ---------------------------------------------------------------------------


def make_inner(robot, robot_coll, dof, scales, collinear, n_newton, damping,
               n_unroll_tail=4, adjoint_ridge=1e-9):
    def cost(x_flat, theta, scene):
        phi = features(x_flat, scene, robot, robot_coll, dof, collinear) / scales
        return jnp.dot(theta, phi)

    grad_x = jax.grad(cost, argnums=0)
    hess_x = jax.hessian(cost, argnums=0)

    def gn_system(x, theta, scene):
        """Gauss-Newton gradient and PSD Hessian of sum_k theta_k ||r_k||^2 / s_k."""
        def res_cat(xx):
            rs = residuals(xx, scene, robot, robot_coll, dof, collinear)
            w = jnp.sqrt(theta / scales)
            return jnp.concatenate([wk * r for wk, r in zip(w, rs)])

        r = res_cat(x)
        J = jax.jacobian(res_cat)(x)
        return 2.0 * J.T @ r, 2.0 * J.T @ J

    def step(carry, theta, scene):
        """One damped Gauss-Newton iteration with an accept/reject guard.

        J^T J is PSD by construction, so the step direction is always a descent
        direction and the iteration converges to a genuine stationary point --
        which is the precondition for both finite differences and the implicit
        function theorem to mean anything.
        """
        x, lam = carry
        f = cost(x, theta, scene)
        g, H = gn_system(x, theta, scene)
        n = H.shape[0]
        H = H + lam * (jnp.trace(H) / n + 1.0) * jnp.eye(n, dtype=H.dtype)
        dx = jnp.linalg.solve(H, g)
        dx = jnp.where(jnp.isfinite(dx), dx, 0.0)
        x_new = x - dx
        ok = cost(x_new, theta, scene) <= f
        x = jnp.where(ok, x_new, x)
        # Cap the damping. With a PSD Gauss-Newton Hessian a small lambda already
        # guarantees a descent direction, so an unbounded cap only enables a death
        # spiral: near the optimum the cost decrease drops below floating-point
        # noise, every step is rejected, lambda ratchets up, steps shrink, and the
        # solver freezes with a large residual gradient (measured: cost converged
        # to 7 digits while ||grad|| stalled at 1.3e-2 and lambda reached 1.4e4).
        lam = jnp.clip(jnp.where(ok, lam * 0.3, lam * 3.0), 1e-10, 1e4)
        return (x, lam)

    def newton(x0, theta, scene):
        carry = jax.lax.fori_loop(
            0, n_newton, lambda _, c: step(c, theta, scene), (x0, damping)
        )
        return carry[0]

    def step_plain(x, lam, theta, scene):
        """Ungated Gauss-Newton step, used for the differentiable unroll tail.

        The gated step returns its input unchanged on a rejected iteration, and
        since the unroll head is under stop_gradient that makes the truncated
        unrolled gradient exactly zero -- silently, and most often right at
        convergence where rejections are common.
        """
        g, H = gn_system(x, theta, scene)
        n = H.shape[0]
        H = H + lam * (jnp.trace(H) / n + 1.0) * jnp.eye(n, dtype=H.dtype)
        return x - jnp.linalg.solve(H, g)

    step_plain_remat = jax.checkpoint(step_plain)

    def solve_unrolled(x0, theta, scene):
        """Truncated unrolling: the last `n_unroll_tail` steps carry gradients.

        Backpropagating through all `n_newton` steps is not memory-feasible --
        each step holds a dense inner Jacobian built from a full FK graph over
        the horizon, and the reverse pass exceeds device memory even with
        rematerialization.  That limitation is itself a result: it is exactly the
        cost the implicit adjoint avoids, since it needs only the final iterate.
        """
        n_head = max(0, n_newton - n_unroll_tail)
        x, lam = jax.lax.stop_gradient(
            jax.lax.fori_loop(0, n_head, lambda _, c: step(c, theta, scene), (x0, damping))
        )
        for _ in range(n_newton - n_head):
            x = step_plain_remat(x, lam, theta, scene)
        return x

    def inner_grad_norm(x0, theta, scene):
        """Stationarity residual of the inner solve -- implicit diff assumes ~0."""
        return jnp.linalg.norm(grad_x(newton(x0, theta, scene), theta, scene))

    # -- implicit: adjoint through the stationarity condition -------------------
    @jax.custom_vjp
    def solve_implicit(x0, theta, scene):
        return newton(x0, theta, scene)

    def _fwd(x0, theta, scene):
        xs = jax.lax.stop_gradient(newton(x0, theta, scene))
        return xs, (xs, theta, scene)

    def _bwd(res, g_out):
        xs, theta, scene = res
        H = hess_x(xs, theta, scene)
        # Ridge only for numerical invertibility.  Reusing the LM damping here
        # would be a bug: that damping exists to make the *forward* step safe,
        # and it is many orders of magnitude larger than what conditioning needs,
        # so it biases H^{-1} and corrupts the adjoint.
        n = H.shape[0]
        H = H + adjoint_ridge * (jnp.trace(H) / n + 1.0) * jnp.eye(n, dtype=H.dtype)
        # dx*/dtheta = -H^{-1} B, so the cotangent is -B^T H^{-T} g_out.
        u = jnp.linalg.solve(H.T, g_out)
        _, vjp_theta = jax.vjp(lambda th: grad_x(xs, th, scene), theta)
        (g_theta,) = vjp_theta(u)
        zero_scene = jax.tree.map(jnp.zeros_like, scene)
        return jnp.zeros_like(xs), -g_theta, zero_scene

    solve_implicit.defvjp(_fwd, _bwd)

    return cost, grad_x, solve_unrolled, solve_implicit, inner_grad_norm


def straight_line_seed(scene, dof):
    alphas = jnp.linspace(0.0, 1.0, N_TIMESTEPS)[1:-1, None]
    return ((1 - alphas) * scene.q_start + alphas * scene.q_goal).reshape(-1)


# ---------------------------------------------------------------------------
# Outer loss
# ---------------------------------------------------------------------------


def make_outer(robot, robot_coll, dof, ee_index, solver, scenes, demos, seeds):
    """L(z) over all contexts, with theta = softmax(z)."""

    def per_scene(z, scene, demo, x0):
        theta = jax.nn.softmax(z)
        xs = solver(x0, theta, scene)
        p = ee_positions(unpack(xs, scene, dof), robot, ee_index)
        p_demo = ee_positions(demo, robot, ee_index)
        return jnp.mean(jnp.sum((p - p_demo) ** 2, axis=-1))

    def loss(z):
        vals = jax.vmap(per_scene, in_axes=(None, 0, 0, 0))(z, scenes, demos, seeds)
        return jnp.mean(vals)

    return loss


# ---------------------------------------------------------------------------
# Optimizers over z
# ---------------------------------------------------------------------------


def adam(grad_fn, z0, n_steps, lr, solves_per_step):
    """Adam on z, returning the best iterate seen, not the last one.

    CMA-ES reports its best-ever candidate, so returning Adam's final iterate
    would compare a noisy last step against a curated best and make the gradient
    methods look worse than they are -- especially at high demonstration noise,
    where the outer landscape is rough.  Both now report best-so-far.  The loss
    at z_t is already computed by grad_fn, so this costs no extra solves.
    """
    z, m, v = z0, jnp.zeros_like(z0), jnp.zeros_like(z0)
    history = []
    best_val, best_z = np.inf, z0
    for t in range(1, n_steps + 1):
        val, g = grad_fn(z)
        fval = float(val)
        if fval < best_val:
            best_val, best_z = fval, z
        m = 0.9 * m + 0.1 * g
        v = 0.999 * v + 0.001 * g**2
        mh, vh = m / (1 - 0.9**t), v / (1 - 0.999**t)
        z = z - lr * mh / (jnp.sqrt(vh) + 1e-8)
        history.append((t * solves_per_step, fval))
    return best_z, history


def fd_grad_fn(loss, eps):
    def grad_fn(z):
        val = loss(z)
        g = []
        for k in range(z.shape[0]):
            e = jnp.zeros_like(z).at[k].set(eps)
            g.append((loss(z + e) - val) / eps)
        return val, jnp.stack(g)

    return grad_fn


def cma_es(loss, z0, n_gens, sigma0, seed):
    """Compact (mu/mu_w, lambda)-CMA-ES; avoids a new dependency on `cma`."""
    n = z0.shape[0]
    lam = 4 + int(3 * np.log(n))
    mu = lam // 2
    w = np.log(mu + 0.5) - np.log(np.arange(1, mu + 1))
    w /= w.sum()
    mueff = 1.0 / np.sum(w**2)
    cc = (4 + mueff / n) / (n + 4 + 2 * mueff / n)
    cs = (mueff + 2) / (n + mueff + 5)
    c1 = 2 / ((n + 1.3) ** 2 + mueff)
    cmu = min(1 - c1, 2 * (mueff - 2 + 1 / mueff) / ((n + 2) ** 2 + mueff))
    damps = 1 + 2 * max(0, np.sqrt((mueff - 1) / (n + 1)) - 1) + cs
    chiN = np.sqrt(n) * (1 - 1 / (4 * n) + 1 / (21 * n**2))

    rng = np.random.default_rng(seed)
    mean = np.array(z0, dtype=np.float64)
    C = np.eye(n)
    pc, ps = np.zeros(n), np.zeros(n)
    sigma = sigma0
    history, n_solves = [], 0
    best = (np.inf, mean)

    for gen in range(1, n_gens + 1):
        d, B = np.linalg.eigh(C)
        d = np.sqrt(np.maximum(d, 1e-12))
        Z = rng.standard_normal((lam, n))
        Y = Z @ (B * d).T
        X = mean + sigma * Y
        fs = np.array([float(loss(jnp.asarray(x))) for x in X])
        n_solves += lam
        order = np.argsort(fs)
        if fs[order[0]] < best[0]:
            best = (fs[order[0]], X[order[0]].copy())
        Yw = w @ Y[order[:mu]]
        mean = mean + sigma * Yw

        Cinv_half = (B / d) @ B.T
        ps = (1 - cs) * ps + np.sqrt(cs * (2 - cs) * mueff) * (Cinv_half @ Yw)
        hsig = np.linalg.norm(ps) / np.sqrt(1 - (1 - cs) ** (2 * gen)) / chiN < 1.4 + 2 / (n + 1)
        pc = (1 - cc) * pc + hsig * np.sqrt(cc * (2 - cc) * mueff) * Yw
        Ymu = Y[order[:mu]]
        C = (
            (1 - c1 - cmu) * C
            + c1 * (np.outer(pc, pc) + (1 - hsig) * cc * (2 - cc) * C)
            + cmu * (Ymu.T * w) @ Ymu
        )
        sigma *= np.exp((cs / damps) * (np.linalg.norm(ps) / chiN - 1))
        history.append((n_solves, float(fs[order[0]])))

    return jnp.asarray(best[1]), history


def kkt_fit(grad_x, scenes, demos, dof, n_steps=400, lr=0.05):
    """Feature matching: min_theta || sum_k theta_k grad_x phi_k(x_demo) ||^2.

    Uses zero forward trajectory-optimization solves.
    """
    e = jnp.eye(K)

    def stacked_B(scene, demo):
        x_demo = demo[1:-1].reshape(-1)
        cols = [grad_x(x_demo, e[k], scene) for k in range(K)]
        return jnp.stack(cols, axis=-1)  # (n_x, K)

    Bs = jax.vmap(stacked_B)(scenes, demos)
    G = jnp.einsum("bik,bil->kl", Bs, Bs) / Bs.shape[0]

    def resid(z):
        theta = jax.nn.softmax(z)
        return theta @ G @ theta

    grad_fn = jax.jit(jax.value_and_grad(resid))
    z, _ = adam(lambda zz: grad_fn(zz), jnp.zeros(K), n_steps, lr, 0)
    return z, G


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


def simplex_metrics(theta_hat, theta_star):
    l1 = float(jnp.sum(jnp.abs(theta_hat - theta_star)))
    cos = float(
        jnp.dot(theta_hat, theta_star)
        / (jnp.linalg.norm(theta_hat) * jnp.linalg.norm(theta_star))
    )
    return l1, cos


def evaluate(z, solver, cost, robot, dof, ee_index, scenes, demos, seeds, theta_star):
    theta = jax.nn.softmax(z)

    def one(scene, demo, x0):
        x_hat = solver(x0, theta, scene)
        x_star = solver(x0, theta_star, scene)
        q_hat = unpack(x_hat, scene, dof)
        regret = cost(x_hat, theta_star, scene) - cost(x_star, theta_star, scene)
        ee_rmse = jnp.sqrt(
            jnp.mean(
                jnp.sum(
                    (ee_positions(q_hat, robot, ee_index) - ee_positions(demo, robot, ee_index))
                    ** 2,
                    axis=-1,
                )
            )
        )
        return regret, ee_rmse

    regret, ee_rmse = jax.vmap(one)(scenes, demos, seeds)
    l1, cos = simplex_metrics(theta, theta_star)
    return {
        "theta_hat": [float(t) for t in theta],
        "theta_l1": l1,
        "theta_cos": cos,
        "regret": float(jnp.mean(regret)),
        "ee_rmse": float(jnp.mean(ee_rmse)),
    }


# ---------------------------------------------------------------------------
# Scene / demonstration generation
# ---------------------------------------------------------------------------


def sample_scenes(rng, n, q_start, q_goal, robot, robot_coll, dof):
    """Obstacles are anchored *on* the straight-line EE path, then offset.

    This is the crux of identifiability.  If the obstacle never blocks the seed
    path the collision feature is inactive, x*(theta) is the straight line for
    every theta, and no method -- however good its gradients -- can recover the
    weights.  Anchoring on the path and varying the offset/radius makes the
    collision term active to differing degrees across contexts, which is exactly
    the variation the weights are identified from.
    """
    starts, goals = [], []
    for _ in range(n):
        jitter = rng.normal(scale=0.10, size=dof)
        starts.append(np.asarray(q_start) + jitter)
        goals.append(np.asarray(q_goal) - jitter)
    starts, goals = np.stack(starts), np.stack(goals)

    ee_index = robot.links.names.index(EE_LINK)
    centers, radii = [], []
    for i in range(n):
        scene_i = Scene(
            q_start=jnp.asarray(starts[i]),
            q_goal=jnp.asarray(goals[i]),
            obs_center=jnp.zeros(3),
            obs_radius=jnp.ones(1),
        )
        q_seed = unpack(straight_line_seed(scene_i, dof), scene_i, dof)
        p = np.asarray(ee_positions(q_seed, robot, ee_index))
        t = rng.integers(N_TIMESTEPS // 3, 2 * N_TIMESTEPS // 3)
        r = rng.uniform(0.08, 0.14)
        # Offset the obstacle just about one radius off the path: a little less
        # and it blocks, a little more and it is clear.  Anchoring it *on* the
        # path instead leaves the seed deeply penetrating in every context, which
        # saturates the collision feature and destroys the tradeoff.
        direction = rng.normal(size=3)
        direction /= np.linalg.norm(direction)
        centers.append(p[t] + direction * (r + rng.uniform(-0.05, 0.10)))
        radii.append(np.array([r]))

    return Scene(
        q_start=jnp.asarray(starts),
        q_goal=jnp.asarray(goals),
        obs_center=jnp.asarray(np.stack(centers)),
        obs_radius=jnp.asarray(np.stack(radii)),
    )


def calibrate_scales(scenes, robot, robot_coll, dof, collinear, key, n_probe=16, jitter=0.15):
    """Whiten features so weight recovery does not just measure feature scaling.

    Calibrate on *randomly perturbed* trajectories, never on the straight-line
    seed: the seed has exactly zero acceleration, so a seed-based scale for the
    smoothness feature collapses to the numerical floor and silently applies an
    enormous weight to it, pinning x*(theta) to the straight line for every theta.
    """

    def raw(scene, k):
        x0 = straight_line_seed(scene, dof)
        x = x0 + jitter * jax.random.normal(k, x0.shape)
        return features(x, scene, robot, robot_coll, dof, collinear)

    keys = jax.random.split(key, n_probe)
    vals = jax.vmap(jax.vmap(raw, in_axes=(None, 0)), in_axes=(0, None))(scenes, keys)
    vals = vals.reshape(-1, K)
    scales = jnp.mean(jnp.abs(vals), axis=0)
    assert bool(jnp.all(scales > 1e-8)), f"degenerate feature scale: {scales}"
    return scales


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def gradient_check(loss_implicit, loss_unrolled, z0, eps_list=(1e-2, 1e-3, 1e-4, 1e-5)):
    """Agreement between the implicit adjoint, the unrolled gradient, and FD.

    If these disagree, every result downstream is meaningless -- so this runs
    first and is reported in the paper as a correctness precondition.
    """
    gi = jax.grad(loss_implicit)(z0)
    gu = jax.grad(loss_unrolled)(z0)
    cos_iu = float(
        jnp.dot(gi, gu) / (jnp.linalg.norm(gi) * jnp.linalg.norm(gu) + 1e-30)
    )
    print(f"  implicit vs unrolled: cos={cos_iu:.6f} "
          f"|gi|={float(jnp.linalg.norm(gi)):.3e} |gu|={float(jnp.linalg.norm(gu)):.3e}")
    out = {"cos_implicit_unrolled": cos_iu}
    for eps in eps_list:
        gfd = fd_grad_fn(loss_implicit, eps)(z0)[1]
        cos = float(
            jnp.dot(gi, gfd) / (jnp.linalg.norm(gi) * jnp.linalg.norm(gfd) + 1e-30)
        )
        rel = float(jnp.linalg.norm(gi - gfd) / (jnp.linalg.norm(gi) + 1e-30))
        out[f"fd_eps_{eps:g}"] = {"cos": cos, "rel_err": rel}
        print(f"  implicit vs fd(eps={eps:g}): cos={cos:.6f} rel_err={rel:.3e}")
    return out


def run_trial(
    robot,
    robot_coll,
    dof,
    ee_index,
    theta_star,
    n_contexts,
    seed,
    demo_noise,
    n_newton,
    damping,
    n_steps,
    lr,
    fd_eps,
    collinear,
    q_start,
    q_goal,
    check_grads,
    n_unroll_tail,
    adjoint_ridge,
    conv_tol,
):
    rng = np.random.default_rng(seed)
    # Oversample scenes, then keep only those whose inner solve actually reaches
    # stationarity at theta*.  Both the implicit function theorem and finite
    # differences assume x*(theta) is a converged minimizer; on scenes where the
    # solver plateaus, x* still depends on the solver path and FD picks up
    # sensitivity the adjoint cannot see (measured: gradient agreement falls from
    # cos=0.9999 to cos=0.59 on such scenes).  Discarding them is a stated
    # precondition of the experiment, and the discard rate is reported.
    pool = sample_scenes(rng, n_contexts * 4, q_start, q_goal, robot, robot_coll, dof)
    scales_pool = calibrate_scales(
        pool, robot, robot_coll, dof, collinear, jax.random.key(seed)
    )
    _, _, _, _, ign_pool = make_inner(
        robot, robot_coll, dof, scales_pool, collinear, n_newton, damping,
        n_unroll_tail, adjoint_ridge,
    )
    x0_pool = jax.vmap(lambda s: straight_line_seed(s, dof))(pool)
    gn_pool = np.asarray(
        jax.vmap(lambda x0, s: ign_pool(x0, theta_star, s))(x0_pool, pool)
    )
    keep = np.flatnonzero(gn_pool < conv_tol)
    n_pool = len(gn_pool)
    if len(keep) < n_contexts:
        raise RuntimeError(
            f"only {len(keep)}/{n_pool} scenes converged below {conv_tol:g}; "
            "loosen conv_tol or raise n_newton"
        )
    # Rate must be measured before truncating to n_contexts, otherwise it just
    # reports 1 - n_contexts/n_pool and carries no information about the solver.
    discard_rate = 1.0 - len(keep) / n_pool
    keep = keep[:n_contexts]
    scenes = jax.tree.map(lambda a: a[keep], pool)
    scales = calibrate_scales(
        scenes, robot, robot_coll, dof, collinear, jax.random.key(seed)
    )

    cost, grad_x, solve_unrolled, solve_implicit, inner_grad_norm = make_inner(
        robot, robot_coll, dof, scales, collinear, n_newton, damping, n_unroll_tail
    )

    seeds_x0 = jax.vmap(lambda s: straight_line_seed(s, dof))(scenes)

    # -- demonstrations: optimal under theta_star, plus observation noise -------
    x_demo = jax.vmap(lambda x0, s: solve_unrolled(x0, theta_star, s))(seeds_x0, scenes)
    demos = jax.vmap(lambda x, s: unpack(x, s, dof))(x_demo, scenes)
    noise = jnp.asarray(rng.normal(scale=demo_noise, size=demos.shape))
    noise = noise.at[:, 0].set(0.0).at[:, -1].set(0.0)  # endpoints are observed exactly
    demos = demos + noise

    # -- identifiability certificate: Gram matrix of the feature gradients ------
    _, G = kkt_fit(grad_x, scenes, demos, dof, n_steps=1, lr=0.0)
    eig = np.linalg.eigvalsh(np.asarray(G) / (np.trace(np.asarray(G)) / K + 1e-30))
    certificate = {
        "scene_discard_rate": float(discard_rate),
        "gram_lambda_min": float(eig[0]),
        "gram_cond": float(eig[-1] / max(eig[0], 1e-30)),
    }

    z0 = jnp.asarray(rng.normal(scale=0.5, size=K))
    results = {}

    # Inner-solve stationarity: the implicit adjoint is only valid at a KKT point.
    gnorm = jax.vmap(lambda x0, s: inner_grad_norm(x0, theta_star, s))(seeds_x0, scenes)
    certificate["inner_grad_norm_max"] = float(jnp.max(gnorm))
    certificate["inner_grad_norm_med"] = float(jnp.median(gnorm))

    if check_grads:
        print("  gradient check:")
        certificate["gradients"] = gradient_check(
            jax.jit(make_outer(robot, robot_coll, dof, ee_index, solve_implicit,
                               scenes, demos, seeds_x0)),
            jax.jit(make_outer(robot, robot_coll, dof, ee_index, solve_unrolled,
                               scenes, demos, seeds_x0)),
            z0,
        )

    def finish(name, z, history, wall, solves):
        solver = jax.jit(solve_implicit)
        m = evaluate(
            z, solver, cost, robot, dof, ee_index, scenes, demos, seeds_x0, theta_star
        )
        m.update({"wall_s": wall, "n_solves": solves, "history": history})
        results[name] = m
        print(
            f"    {name:9s} l1={m['theta_l1']:.3f} cos={m['theta_cos']:.4f} "
            f"regret={m['regret']:.3e} ee_rmse={m['ee_rmse']:.4f} "
            f"solves={solves} {wall:.1f}s"
        )

    solves_per_context = n_contexts

    for name, solver in (("implicit", solve_implicit), ("unrolled", solve_unrolled)):
        loss = make_outer(
            robot, robot_coll, dof, ee_index, solver, scenes, demos, seeds_x0
        )
        gf = jax.jit(jax.value_and_grad(loss))
        gf(z0)[0].block_until_ready()  # exclude compilation from the timing
        t0 = time.perf_counter()
        z, hist = adam(gf, z0, n_steps, lr, solves_per_context)
        wall = time.perf_counter() - t0
        finish(name, z, hist, wall, n_steps * solves_per_context)

    loss_i = jax.jit(
        make_outer(robot, robot_coll, dof, ee_index, solve_implicit, scenes, demos, seeds_x0)
    )
    loss_i(z0).block_until_ready()

    t0 = time.perf_counter()
    z, hist = adam(fd_grad_fn(loss_i, fd_eps), z0, n_steps, lr, (K + 1) * solves_per_context)
    finish("fd", z, hist, time.perf_counter() - t0, n_steps * (K + 1) * solves_per_context)

    t0 = time.perf_counter()
    n_gens = max(1, n_steps // 4)
    z, hist = cma_es(loss_i, z0, n_gens, sigma0=0.5, seed=seed)
    finish("cmaes", z, hist, time.perf_counter() - t0, hist[-1][0] * solves_per_context)

    t0 = time.perf_counter()
    z, _ = kkt_fit(grad_x, scenes, demos, dof)
    finish("kkt", z, [], time.perf_counter() - t0, 0)

    # -- bookends ---------------------------------------------------------------
    finish("oracle", jnp.log(theta_star + 1e-30), [], 0.0, 0)
    finish("random", z0, [], 0.0, 0)

    return {"certificate": certificate, "methods": results}


def main(
    urdf_path: str = "resources/panda/panda_spherized.urdf",
    srdf_path: str = "resources/panda/panda.srdf",
    mesh_dir: str = "resources/panda/meshes",
    n_contexts: tuple[int, ...] = (1, 5, 20),
    n_seeds: int = 5,
    n_timesteps: int = 24,
    n_newton: int = 40,
    damping: float = 1e-2,
    n_outer_steps: int = 60,
    lr: float = 0.15,
    fd_eps: float = 1e-4,
    demo_noise: float = 0.0,
    collinear_control: bool = False,
    check_grads: bool = True,
    n_unroll_tail: int = 4,
    adjoint_ridge: float = 1e-9,
    conv_tol: float = 1e-5,
    out: str = "e1_results.json",
):
    if not jax.config.jax_enable_x64:
        print(
            "WARNING: x64 is OFF. The implicit adjoint inverts the inner Hessian; "
            "run with JAX_ENABLE_X64=1 or treat the gradients as float32-noisy."
        )
    global N_TIMESTEPS
    N_TIMESTEPS = n_timesteps
    print(f"jax devices: {jax.devices()}  T={N_TIMESTEPS}")

    urdf = yourdfpy.URDF.load(urdf_path, mesh_dir=mesh_dir)
    robot = pk.Robot.from_urdf(urdf)
    robot_coll = pk.collision.RobotCollisionSpherized.from_urdf(urdf, srdf_path=srdf_path)
    dof = robot.joints.num_actuated_joints
    ee_index = robot.links.names.index(EE_LINK)

    q_start = np.array([0.0, -0.6, 0.0, -2.2, 0.0, 1.6, 0.8])[:dof]
    q_goal = np.array([0.9, -0.2, 0.0, -1.8, 0.0, 1.7, 0.8])[:dof]

    theta_star = jnp.asarray([0.5, 0.3, 0.2])
    print(f"theta* = {np.asarray(theta_star)}  ({', '.join(FEATURE_NAMES)})")

    all_results = {}
    for m in n_contexts:
        for seed in range(n_seeds):
            print(f"[M={m} seed={seed}]")
            r = run_trial(
                robot, robot_coll, dof, ee_index, theta_star, m, seed, demo_noise,
                n_newton, damping, n_outer_steps, lr, fd_eps, collinear_control,
                q_start, q_goal, check_grads, n_unroll_tail, adjoint_ridge, conv_tol,
            )
            print(f"    gram: {r['certificate']}")
            all_results[f"M{m}_s{seed}"] = r

    with open(out, "w") as f:
        json.dump(
            {
                "theta_star": [float(t) for t in theta_star],
                "feature_names": list(FEATURE_NAMES),
                "collinear_control": collinear_control,
                "demo_noise": demo_noise,
                "results": all_results,
            },
            f,
            indent=2,
        )
    print(f"\nwrote {out}")

    # -- aggregate: median +/- IQR over seeds, per M ---------------------------
    print("\n=== median theta_l1 (IQR) over seeds ===")
    methods = ["implicit", "unrolled", "fd", "cmaes", "kkt", "random"]
    print(f"{'M':>4s} " + " ".join(f"{m:>16s}" for m in methods))
    for m in n_contexts:
        row = []
        for name in methods:
            v = [all_results[f"M{m}_s{s}"]["methods"][name]["theta_l1"] for s in range(n_seeds)]
            q1, med, q3 = np.percentile(v, [25, 50, 75])
            row.append(f"{med:6.3f}({q3 - q1:5.3f})")
        print(f"{m:>4d} " + " ".join(f"{r:>16s}" for r in row))


if __name__ == "__main__":
    tyro.cli(main)
