"""E1: identifiability and robustness on the 7-DoF Panda.

Ground-truth cost weights are known.  Demonstrations are generated by solving a
kinematic reach-with-obstacle trajectory optimization under those weights; each
method must recover them from the demonstrated trajectories alone.

    inner:  x*(theta, c) = argmin_x sum_k theta_k phi_k(x, c),  theta on the simplex
    outer:  min_z  L(z) = mean_i || p_ee(x*(softmax(z), c_i)) - p_ee(x~_i) ||^2

Methods compared (see `ioc.inner`, `ioc.outer`, `ioc.analytic` for the theory):

    implicit   custom_vjp adjoint through the inner KKT point    1 solve / step
    unrolled   reverse-mode through the last few Newton steps    1 solve / step
    fd         finite differences on L(z)                      K+1 solves / step
    cmaes      derivative-free search on z                 population / generation
    kkt        Inverse-KKT stationarity residual                 0 solves
    cioc       Continuous IOC (Laplace approx., Levine & Koltun)  0 solves

The sweep axes are the number of demonstration contexts M and the demonstration
noise sigma.  The sigma sweep is the headline: with noiseless demonstrations the
demonstration is an exact stationary point of the true cost, so Inverse KKT
recovers theta* exactly at zero solves and differentiating through the optimizer
buys nothing.  The claim being tested is a *robustness* claim -- that solve-based
methods degrade gracefully as demonstrations become suboptimal, where
stationarity-based fitting does not.

Run under float64: the implicit adjoint inverts the inner Hessian.

    XLA_PYTHON_CLIENT_PREALLOCATE=false JAX_ENABLE_X64=1 CUDA_VISIBLE_DEVICES=0 \
        python -m ioc.robot.e1_identifiability
"""

import json
import time

import jax
import jax.numpy as jnp
import numpy as np
import tyro

from ioc import analytic, metrics, outer as outer_opt
from ioc.inner import make_inner_solver
from ioc.robot import bases, problem as prob
from pyroffi.optimization_engines import DynamicsTrajOptConfig, dynamics_trajopt


def make_dynamics_forward_solver(opt_cfg=DynamicsTrajOptConfig()):
    """Wrap pyroffi's dynamics-aware L-BFGS engine as an `inner.forward_solver`."""

    def forward_solver(x0, cost_fn):
        return dynamics_trajopt(x0, cost_fn, opt_cfg)

    return forward_solver


def gradient_check(loss_implicit, loss_unrolled, z0, eps_list=(1e-2, 1e-3, 1e-4, 1e-5)):
    """Agreement between the implicit adjoint, the unrolled gradient, and FD.

    If these disagree, every result downstream is meaningless -- so this runs
    first and is reported as a correctness precondition.  Per-context agreement,
    not just the aggregate, is what catches silent failures: a minority of
    non-stationary contexts hides inside a good-looking mean.
    """
    gi = jax.grad(loss_implicit)(z0)
    gu = jax.grad(loss_unrolled)(z0)
    out = {"cos_implicit_unrolled": metrics.cosine(gi, gu)}
    print(f"  implicit vs unrolled: cos={out['cos_implicit_unrolled']:.6f} "
          f"|gi|={float(jnp.linalg.norm(gi)):.3e} |gu|={float(jnp.linalg.norm(gu)):.3e}")
    for eps in eps_list:
        gfd = outer_opt.fd_grad_fn(loss_implicit, eps)(z0)[1]
        cos = metrics.cosine(gi, gfd)
        rel = float(jnp.linalg.norm(gi - gfd) / (jnp.linalg.norm(gi) + 1e-30))
        out[f"fd_eps_{eps:g}"] = {"cos": cos, "rel_err": rel}
        print(f"  implicit vs fd(eps={eps:g}): cos={cos:.6f} rel_err={rel:.3e}")
    return out


def run_trial(
    problem, theta_star, n_contexts, seed, demo_noise, n_newton, damping, n_steps,
    lr, fd_eps, collinear, check_grads, n_unroll_tail, adjoint_ridge, conv_tol,
):
    residual_fn, names = bases.kinematic(problem, "k3", collinear=collinear)
    K = len(names)
    rng = np.random.default_rng(seed)

    del damping  # no longer meaningful: the internal GN loop it damped is gone
    forward_solver = make_dynamics_forward_solver(
        DynamicsTrajOptConfig(n_iters=n_newton, grad_tol=min(conv_tol, 1e-6)))
    unrolled_forward_solver = make_dynamics_forward_solver(
        DynamicsTrajOptConfig(n_iters=n_newton, early_stop=False, unroll_tail=n_unroll_tail))

    def build(scales):
        return make_inner_solver(
            residual_fn, scales, adjoint_ridge=adjoint_ridge,
            forward_solver=forward_solver,
            unrolled_forward_solver=unrolled_forward_solver,
        )

    # Oversample contexts, then keep only those whose inner solve reaches
    # stationarity at theta* (see `prob.screen_scenes`).
    pool = problem.sample_scenes(rng, n_contexts * 4)
    scales_pool = problem.calibrate(residual_fn, pool, jax.random.key(seed))
    scenes, discard_rate, _ = prob.screen_scenes(
        problem, pool, build(scales_pool).stationarity, theta_star, conv_tol,
        n_contexts,
    )

    scales = problem.calibrate(residual_fn, scenes, jax.random.key(seed))
    inner = build(scales)

    x0s, _, demos = prob.make_demos(
        problem, inner.solve_implicit, scenes, theta_star, rng, demo_noise
    )

    # Identifiability certificate: the Gram matrix of the feature gradients at
    # the demonstrations.  lambda_min ~ 0 means a feature combination the
    # demonstrations do not excite, so a large weight error along it is a
    # property of the data rather than of any optimizer.
    _, G = analytic.kkt_fit(
        inner.grad_x, scenes, demos, K, n_steps=1, lr=0.0, return_gram=True
    )
    eig = np.linalg.eigvalsh(np.asarray(G) / (np.trace(np.asarray(G)) / K + 1e-30))
    gnorm = jax.vmap(lambda x0, s: inner.stationarity(x0, theta_star, s))(x0s, scenes)
    certificate = {
        "scene_discard_rate": float(discard_rate),
        "gram_lambda_min": float(eig[0]),
        "gram_cond": float(eig[-1] / max(eig[0], 1e-30)),
        "inner_grad_norm_max": float(jnp.max(gnorm)),
        "inner_grad_norm_med": float(jnp.median(gnorm)),
    }

    z0 = jnp.asarray(rng.normal(scale=0.5, size=K))
    results = {}

    if check_grads:
        print("  gradient check:")
        certificate["gradients"] = gradient_check(
            jax.jit(prob.make_outer(problem, inner.solve_implicit, scenes, demos, x0s)),
            jax.jit(prob.make_outer(problem, inner.solve_unrolled, scenes, demos, x0s)),
            z0,
        )

    def finish(name, z, history, wall, solves):
        m = prob.evaluate(
            problem, z, jax.jit(inner.solve_implicit), inner.cost, scenes, demos,
            x0s, theta_star,
        )
        m.update({"wall_s": wall, "n_solves": solves, "history": history})
        results[name] = m
        print(f"    {name:9s} l1={m['theta_l1']:.3f} cos={m['theta_cos']:.4f} "
              f"regret={m['regret']:.3e} ee_rmse={m['ee_rmse']:.4f} "
              f"solves={solves} {wall:.1f}s")

    per_step = n_contexts  # one forward solve per context

    for name, solver in (("implicit", inner.solve_implicit),
                         ("unrolled", inner.solve_unrolled)):
        loss = prob.make_outer(problem, solver, scenes, demos, x0s)
        gf = jax.jit(jax.value_and_grad(loss))
        gf(z0)[0].block_until_ready()  # exclude compilation from the timing
        t0 = time.perf_counter()
        z, hist = outer_opt.adam(
            gf, z0, lr=lr, n_steps=n_steps, solves_per_step=per_step
        )
        finish(name, z, hist, time.perf_counter() - t0, n_steps * per_step)

    loss_i = jax.jit(
        prob.make_outer(problem, inner.solve_implicit, scenes, demos, x0s)
    )
    loss_i(z0).block_until_ready()

    t0 = time.perf_counter()
    z, hist = outer_opt.adam(
        outer_opt.fd_grad_fn(loss_i, fd_eps), z0, lr=lr, n_steps=n_steps,
        solves_per_step=(K + 1) * per_step,
    )
    finish("fd", z, hist, time.perf_counter() - t0, n_steps * (K + 1) * per_step)

    t0 = time.perf_counter()
    z, hist = outer_opt.cma_es(
        loss_i, z0, n_gens=max(1, n_steps // 4), sigma0=0.5, seed=seed
    )
    finish("cmaes", z, hist, time.perf_counter() - t0, hist[-1][0] * per_step)

    t0 = time.perf_counter()
    z = analytic.kkt_fit(inner.grad_x, scenes, demos, K)
    finish("kkt", z, [], time.perf_counter() - t0, 0)

    t0 = time.perf_counter()
    z = analytic.cioc_fit(inner.grad_x, inner.gn_system, scenes, demos, K)
    finish("cioc", z, [], time.perf_counter() - t0, 0)

    # -- bookends: the best achievable and the do-nothing baseline -------------
    finish("oracle", jnp.log(theta_star + 1e-30), [], 0.0, 0)
    finish("random", z0, [], 0.0, 0)

    return {"certificate": certificate, "methods": results}


def main(
    urdf_path: str = "resources/panda/panda_spherized.urdf",
    srdf_path: str = "resources/panda/panda.srdf",
    mesh_dir: str = "resources/panda/meshes",
    n_contexts: tuple[int, ...] = (1, 5, 20),
    n_seeds: int = 5,
    n_timesteps: int = 24,
    n_newton: int = 40,
    damping: float = 1e-2,
    n_outer_steps: int = 60,
    lr: float = 0.15,
    fd_eps: float = 1e-4,
    demo_noise: float = 0.0,
    collinear_control: bool = False,
    check_grads: bool = True,
    n_unroll_tail: int = 2,
    adjoint_ridge: float = 1e-9,
    conv_tol: float = 1e-5,
    out: str = "e1_results.json",
):
    if not jax.config.jax_enable_x64:
        print("WARNING: x64 is OFF. The implicit adjoint inverts the inner Hessian; "
              "run with JAX_ENABLE_X64=1 or treat the gradients as float32-noisy.")
    problem = prob.RobotProblem.load(urdf_path, srdf_path, mesh_dir, n_timesteps)
    print(f"jax devices: {jax.devices()}  T={n_timesteps}")

    theta_star = jnp.asarray([0.5, 0.3, 0.2])
    print(f"theta* = {np.asarray(theta_star)}  ({', '.join(bases.K3_NAMES)})")

    all_results = {}
    for m in n_contexts:
        for seed in range(n_seeds):
            print(f"[M={m} seed={seed}]")
            r = run_trial(
                problem, theta_star, m, seed, demo_noise, n_newton, damping,
                n_outer_steps, lr, fd_eps, collinear_control, check_grads,
                n_unroll_tail, adjoint_ridge, conv_tol,
            )
            print(f"    gram: {r['certificate']}")
            all_results[f"M{m}_s{seed}"] = r

    with open(out, "w") as f:
        json.dump({
            "theta_star": [float(t) for t in theta_star],
            "feature_names": list(bases.K3_NAMES),
            "collinear_control": collinear_control,
            "demo_noise": demo_noise,
            "results": all_results,
        }, f, indent=2)
    print(f"\nwrote {out}")

    print("\n=== median theta_l1 (IQR) over seeds ===")
    methods = ["implicit", "unrolled", "fd", "cmaes", "kkt", "cioc", "random"]
    print(f"{'M':>4s} " + " ".join(f"{m:>16s}" for m in methods))
    for m in n_contexts:
        row = []
        for name in methods:
            v = [all_results[f"M{m}_s{s}"]["methods"][name]["theta_l1"]
                 for s in range(n_seeds)]
            q1, med, q3 = np.percentile(v, [25, 50, 75])
            row.append(f"{med:6.3f}({q3 - q1:5.3f})")
        print(f"{m:>4d} " + " ".join(f"{r:>16s}" for r in row))


if __name__ == "__main__":
    tyro.cli(main)
